
# Edit this if your computer has things set up differently.

sketch-program:
	gcc -std=c99 -Wall -O3 -pedantic -I /Library/Frameworks/SDL2.framework/Headers -F/Library/Frameworks -framework SDL2 sketch.c display.c -o sketch
